name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          # cname: mysite.com # Or anything else
          # Use if you have a custom domain for your site.
          branch: master
          # Use if your site is not hosted on the gh-pages branch.
          repo: OpenSecuritySummit/oss2020.github.io
          # Use if your pushing to a different repo.
          # Dont add ".git" to the end of the URL (youl'll get 404s).
          hugoVersion: extended_0.58.3
          # Use if your site requires a specific version of Hugo
          # Append "extended_" to the begining to use Hugo Extended
          args: --gc --minify --cleanDestinationDir
          # Use if you want to pass some custom arguments to Hugo
